// @vitest-environment jsdom
import {afterEach,describe,it,expect} from 'vitest';
import {act,cleanup,renderHook,render,screen,fireEvent} from '@testing-library/react';
import type {ReactNode} from 'react';
import {AppProvider} from '../AppContext';
import App from '../App';
import {AdminProvider,useAdmin} from './AdminContext';
import {firstAdminPage,permissions,rolePermissions,validMatrix} from './model';
afterEach(()=>{cleanup();window.history.replaceState(null,'','/')});
const wrapper=({children}:{children:ReactNode})=><AppProvider><AdminProvider>{children}</AdminProvider></AppProvider>;
const setup=()=>renderHook(()=>useAdmin(),{wrapper});
const input={name:'Invited Tester',email:'tester@example.com',phone:'',role:'ADMIN' as const};
describe('Dedicated VIG access',()=>{
 it('starts signed out, rejects bad credentials, logs out and resets safely',()=>{const h=setup();expect(h.result.current.current).toBeUndefined();act(()=>expect(h.result.current.login('superadmin@vig.example','bad').error).toBe('credentials'));act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));expect(h.result.current.can('P21')).toBe(true);act(()=>h.result.current.logout());expect(h.result.current.can('P21')).toBe(false);act(()=>h.result.current.login('admin@vig.example','VigDemo@2026'));act(()=>h.result.current.reset());expect(h.result.current.current).toBeUndefined();expect(h.result.current.can('P01')).toBe(false)});
 it('allows delegated invitations only with both permissions, and prevents matrix elevation',()=>{const h=setup();act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));const m=structuredClone(h.result.current.store.matrix);m.ADMIN.push('P12','P13');act(()=>expect(h.result.current.configure(m,1).ok).toBe(true));act(()=>h.result.current.login('admin@vig.example','VigDemo@2026'));act(()=>expect(h.result.current.invite(input).error).toBe('permission'));act(()=>expect(h.result.current.configure(m,2).error).toBe('permission'));act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));m.ADMIN.push('P19');act(()=>h.result.current.configure(m,2));act(()=>h.result.current.login('admin@vig.example','VigDemo@2026'));act(()=>expect(h.result.current.invite(input).ok).toBe(true));act(()=>expect(h.result.current.updateUser('sa',1,'ADMIN').error).toBe('protected'));act(()=>expect(h.result.current.updateUser('operator',1,'SA').error).toBe('roles'))});
 it('accepts one of two roles and revokes the other without granting a union',()=>{const h=setup();act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));act(()=>h.result.current.invite(input));act(()=>expect(h.result.current.invite(input).error).toBe('duplicate'));act(()=>expect(h.result.current.invite({...input,role:'OPERATOR'}).ok).toBe(true));const u=h.result.current.store.users.find(u=>u.email===input.email)!;expect(u.role).toBeNull();expect(permissions(u)).toEqual([]);const invites=h.result.current.store.invites.filter(i=>i.userId===u.id);act(()=>h.result.current.logout());act(()=>expect(h.result.current.accept(invites[1].token,'NewDemo@2026','NewDemo@2026').ok).toBe(true));expect(h.result.current.current?.role).toBe('OPERATOR');expect(h.result.current.store.invites.find(i=>i.id===invites[0].id)?.status).toBe('revoked');expect(h.result.current.store.audit[0].actor).toBe(input.name);act(()=>h.result.current.logout());act(()=>expect(h.result.current.login(input.email,'NewDemo@2026').ok).toBe(true));expect(JSON.stringify(h.result.current.store)).not.toContain('NewDemo@2026')});
 it('saves matrices atomically, rejects stale revisions and protected changes',()=>{const h=setup();act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));const m=structuredClone(h.result.current.store.matrix);m.ADMIN=m.ADMIN.filter(p=>p!=='P01');act(()=>expect(h.result.current.configure(m,1).error).toBe('dependencies'));expect(h.result.current.store.matrix).toEqual(rolePermissions);const good=structuredClone(rolePermissions);good.ADMIN=['P20'];act(()=>expect(h.result.current.configure(good,1).ok).toBe(true));act(()=>expect(h.result.current.configure(rolePermissions,1).error).toBe('stale'));act(()=>h.result.current.login('admin@vig.example','VigDemo@2026'));expect(h.result.current.can('P01')).toBe(false);expect(firstAdminPage(h.result.current.current,h.result.current.store.matrix)).toBe('/admin/permissions');const invalid=structuredClone(rolePermissions);invalid.OPERATOR.push('P21');expect(validMatrix(invalid)).toBe(false)});
 it('separates account and access, preserves role on suspension and denies stale saves',()=>{const h=setup();act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));act(()=>expect(h.result.current.updateUser('admin',1,undefined,'suspended').ok).toBe(true));const u=h.result.current.store.users.find(u=>u.id==='admin')!;expect(u.account).toBe('active');expect(u.role).toBe('ADMIN');expect(permissions(u)).toEqual([]);act(()=>expect(h.result.current.updateUser('admin',1,'OPERATOR').error).toBe('stale'));act(()=>expect(h.result.current.updateUser('admin',2,undefined,'active').ok).toBe(true));act(()=>expect(h.result.current.updateUser('admin',3,undefined,'removed').ok).toBe(true));act(()=>expect(h.result.current.updateUser('admin',4,'OPERATOR').ok).toBe(true));expect(h.result.current.store.users.find(u=>u.id==='admin')?.access).toBe('active')});
 it('retries a failed delivery without duplicating the invitation',()=>{const h=setup();act(()=>h.result.current.login('superadmin@vig.example','VigDemo@2026'));const i=h.result.current.store.invites[0];i.delivery='failed';const count=h.result.current.store.invites.length;act(()=>expect(h.result.current.retryDelivery(i.id).ok).toBe(true));expect(h.result.current.store.invites).toHaveLength(count);act(()=>expect(h.result.current.retryDelivery(i.id).error).toBe('stale'))});
 it('protects clean and legacy admin routes and removes public login entry',()=>{window.history.replaceState(null,'','/#/admin/users');render(<App/>);expect(window.location.pathname).toBe('/admin/login');expect(screen.getByLabelText('Tên đăng nhập')).toBeTruthy();fireEvent.change(screen.getByLabelText('Tên đăng nhập'),{target:{value:'superadmin@vig.example'}});fireEvent.change(screen.getByLabelText('Mật khẩu'),{target:{value:'VigDemo@2026'}});fireEvent.click(screen.getByRole('button',{name:'Đăng nhập'}));expect(window.location.pathname).toBe('/admin/users');cleanup();window.history.replaceState(null,'','/home');render(<App/>);expect(document.querySelector('a[href="/admin/login"]')).toBeNull();expect(document.querySelector('a[href="/login"]')).toBeNull()});
});
