import {optionText} from './copy';
import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useApp,tr} from '../AppContext';
import {parks,assets} from '../data';
import {useAdmin} from './AdminContext';
import {Access,AdminNotice,Confirm,Message,useText} from './ui';
import {contentErrors,publicationIssues,isPark,type Content,type ContentKind} from './model';
import {fieldLabels} from './fieldLabels';
import {StatePanel,SafeImage} from '../EmptyStates';
import type {IndustrialParkProfile,IndustrialAsset} from '../types';

export const enumOptions:Record<string,string[]>={status:['operational','developing','planned'],region:['North','Central','South'],transaction:['lease','sale'],transactionModes:['lease','sale'],disclosureStatus:['public','not_disclosed','not_available'],verificationStatus:['unverified','reviewed','verified'],visibility:['admin_only','public'],sourceLanguage:['vi','en','zh'],language:['vi','en','zh','multi'],category:['brochure','presentation','masterplan','establishment_decision','enterprise_registration','legal_approval'],priceMode:['specific','negotiable','not_available']};
const typeOptions=(path:string)=>path.startsWith('connectivity')?['port','airport','road','rail','city','logistics']:path.startsWith('media')?['hero','gallery','site_photo','masterplan','map','video']:['industrial_land','ready_built_factory','warehouse','build_to_suit'];
export function blank(value:unknown,key=''):any {
  if(value===null||value===undefined)return null;
  if(Array.isArray(value))return [];
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['conflicts','payment'].includes(k)).map(([k,v])=>[k,blank(v,k)]));
  if(key==='disclosureStatus')return 'not_available';if(key==='verificationStatus')return 'unverified';if(key==='visibility')return 'admin_only';
  if(key==='publicationStatus')return 'draft';if(enumOptions[key])return enumOptions[key][0];
  if(typeof value==='boolean')return false;if(typeof value==='number')return null;
  return key==='unit'?value:'';
}
export function newContent(kind:ContentKind,id=`${kind}-${crypto.randomUUID().slice(0,8)}`):Content {const data=blank(kind==='park'?parks[0]:assets[0]);data.id=id;if(kind==='asset'){data.type='industrial_land';data.unit='ha';data.transaction='lease';data.priceMode='not_available';data.pricingBasis='';data.imageApproved=false;}return data as Content}
const localized=(v:unknown):v is {vi:string;en:string;zh?:string}=>!!v&&typeof v==='object'&&!Array.isArray(v)&&'vi' in v&&'en' in v;
const prefix:Record<string,string>={operator:'',provinceProfile:'',workforce:'',logistics:'',contact:'',phases:'',availability:'',connectivity:'',utilities:'',incentives:'',process:'',documents:'',media:''};
function labelFor(path:string,language:'vi'|'en'|'zh') {const clean=path.replace(/\.\d+/g,''),index=language==='vi'?0:language==='en'?1:2;let label=fieldLabels[clean]||fieldLabels[clean.split('.').at(-1)!]||fieldLabels[`asset.${clean}`];if(!label){const [first,...rest]=clean.split('.');if(first in prefix)label=fieldLabels[rest.join('.')];}return label?.[index]||({vi:'Tiếng Việt',en:'English',zh:'中文',value:language==='vi'?'Giá trị':language==='en'?'Value':'数值',unit:language==='vi'?'Đơn vị':language==='en'?'Unit':'单位',id:'ID',key:language==='vi'?'Mã loại':language==='en'?'Type key':'类型编码',pricingBasis:language==='vi'?'Đơn vị định giá':language==='en'?'Pricing basis':'计价单位',imageApproved:language==='vi'?'Ảnh đã duyệt':language==='en'?'Approved image':'图片已审核',priceMode:language==='vi'?'Chế độ giá':language==='en'?'Price mode':'价格模式'} as Record<string,string>)[clean.split('.').at(-1)!]||clean.split('.').at(-1)!;}
const templates:Record<string,unknown>={...Object.fromEntries(Object.entries(parks[0]).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,(v as unknown[])[0]])), 'operator.portfolioStats':parks[0].operator.portfolioStats[0], 'workforce.salaryBenchmark':parks[0].workforce.salaryBenchmark[0],'logistics.shippingRoutes':parks[0].logistics.shippingRoutes[0],'logistics.indicativeCosts':parks[0].logistics.indicativeCosts[0],'incentives.schedule':parks[0].incentives[0]?.schedule[0]};
function Field({path,value,onChange,errors,disabled=false}:{path:string;value:any;onChange:(v:any)=>void;errors:Record<string,string>;disabled?:boolean}){
  const {language}=useApp(),a=useAdmin(),t=useText();const label=labelFor(path,language),key=path.split('.').at(-1)!,clean=path.replace(/\.\d+/g,'');
  const privileged=['verificationStatus','visibility','approved','imageApproved','verifiedBy','lastVerifiedAt'].includes(key);
  const locked=privileged?!a.can('P08'):disabled;
  if(['conflicts','payment','publicationStatus'].includes(key))return null;
  if(localized(value))return <fieldset className="localized-field"><legend>{label}</legend><div className="form-grid">{(['vi','en','zh'] as const).map(lang=><label key={lang}>{lang.toUpperCase()}<textarea disabled={locked} value={value[lang]||''} onChange={e=>onChange({...value,[lang]:e.target.value})}/></label>)}</div></fieldset>;
  if(Array.isArray(value)){
    const controlled=['suitableIndustries','restrictedIndustries','industries'].includes(key)?[...new Set(parks.flatMap(p=>p.suitableIndustries))]:key==='transactionModes'?['lease','sale']:null;
    if(controlled)return <fieldset><legend>{label}</legend><div className="role-options">{controlled.map(v=><label key={v}><input type="checkbox" disabled={locked} checked={value.includes(v)} onChange={()=>onChange(value.includes(v)?value.filter(x=>x!==v):[...value,v])}/>{v}</label>)}</div></fieldset>;
    return <fieldset className="repeat-field"><legend>{label} ({value.length})</legend>{value.map((item,i)=><div className="repeat-row" key={i}><div className="repeat-head"><b>{label} {i+1}</b><button type="button" className="button" disabled={locked} onClick={()=>onChange(value.filter((_,n)=>n!==i))}>{t('Xóa dòng','Remove row','删除行')}</button></div><Field path={`${path}.${i}`} value={item} errors={errors} disabled={locked} onChange={v=>onChange(value.map((old,n)=>n===i?v:old))}/></div>)}{!value.length&&<p className="muted">{t('Chưa có thông tin. Thêm dòng khi có dữ liệu nguồn.','No information yet. Add a row when source data is available.','暂无资料，请在有来源数据时添加。')}</p>}<button type="button" className="button" disabled={locked} onClick={()=>{let sample=templates[clean]||value[0]||'';let next=blank(sample);if(next&&typeof next==='object'&&!Array.isArray(next)){if('id'in next)next.id=crypto.randomUUID();if('type'in next)next.type=typeOptions(path)[0];if('order'in next)next.order=value.length+1;}onChange([...value,next])}}>{t('Thêm dòng','Add row','添加行')}</button></fieldset>;
  }
  if(value&&typeof value==='object')return <fieldset><legend>{label}</legend><div className="form-grid">{Object.entries(value).map(([k,v])=><Field key={k} path={`${path}.${k}`} value={v} errors={errors} disabled={locked} onChange={next=>onChange({...value,[k]:next})}/>)}</div></fieldset>;
  const opts=key==='type'?typeOptions(path):key==='key'&&path.startsWith('utilities')?['electricity','water','wastewater','roads','road','telecom','security','drainage','fire']:key==='parkId'?a.store.drafts.filter(d=>d.kind==='park').map(d=>d.id):key==='province'?[...new Set(parks.map(p=>p.province))]:key==='status'&&path.startsWith('connectivity')?['operational','construction','planned']:enumOptions[key];
  const error=errors[path]||errors[clean];const number=typeof value==='number'||value===null&&/(value|area|Year|Mva|lat|lng|order|RadiusKm)$/.test(key);const date=/(asOf|From|At|Date)$/.test(key)&&key!=='createdAt';
  return <label className={error?'field-error':''}>{label}{opts?<select disabled={locked} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">{t('Chưa xác định','Not specified','未指定')}</option>{value&&!opts.includes(value)&&<option value={value} disabled>{value} — {t('Giá trị nguồn cũ','Legacy source value','旧来源值')}</option>}{opts.map(v=><option key={v} value={v}>{key==='parkId'?a.store.drafts.find(d=>d.id===v)?.data.name[language]||v:optionText(v,language)}</option>)}</select>:typeof value==='boolean'?<input type="checkbox" disabled={locked} checked={value} onChange={e=>onChange(e.target.checked)}/>:<input disabled={locked||key==='id'} type={number?'number':date?'date':key==='email'?'email':'text'} step={number?'any':undefined} value={value??''} onChange={e=>onChange(number?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}<small>{path}</small>{error&&<span role="alert">{t('Giá trị chưa hợp lệ: ','Invalid value: ','无效数值：')}{error}</span>}</label>;
}
const parkGroups=[['identity','Nhận diện & vị trí','Identity & location','识别与位置',['slug','name','summary','logoText','status','parkType','establishmentYear','totalArea','industrialLandArea','coordinates','address','economicZone','region','province']],['operator','Đơn vị & quỹ đất','Operator & availability','开发商与供应',['operator','phases','availability']],['infrastructure','Hạ tầng & kết nối','Infrastructure & connectivity','基础设施与交通',['utilities','connectivity','amenities']],['workforce','Kinh tế & nhân lực','Economy & workforce','经济与劳动力',['provinceProfile','workforce']],['investment','Đầu tư & logistics','Investment & logistics','投资与物流',['incentives','process','logistics']],['community','Ngành & cộng đồng','Industries & community','产业与社区',['suitableIndustries','restrictedIndustries','environmentalConditions','sustainability','community','tenants']],['media','Media & pháp lý','Media & legal','媒体与法律',['media','documents']],['contact','Liên hệ & nguồn','Contact & sources','联系方式与来源',['contact','sourceLanguage','dataOwner','lastVerifiedAt','verifiedBy']]] as const;
export function ContentList({kind}:{kind:ContentKind}){const a=useAdmin(),{language}=useApp(),t=useText(),[q,setQ]=useState('');const rows=a.store.drafts.filter(d=>d.kind===kind&&`${d.id} ${tr(d.data.name,language)}`.toLowerCase().includes(q.toLowerCase()));return <Access permission="P01"><div className="admin-page workflow-page"><div className="admin-title"><div><span>VIG DATA</span><h1>{kind==='park'?t('Hồ sơ khu công nghiệp','Industrial park records','工业园区档案'):t('Bất động sản công nghiệp','Industrial assets','工业地产')}</h1></div>{a.can('P02')&&<Link className="button primary" to={`/admin/${kind==='park'?'industrial-parks':'assets'}/new`}>{t('Tạo bản nháp','Create draft','创建草稿')}</Link>}</div><AdminNotice/><input className="admin-search" placeholder={t('Tìm tên hoặc mã','Search name or ID','搜索名称或编号')} value={q} onChange={e=>setQ(e.target.value)}/><div className="admin-panel table-scroll"><table className="workflow-table"><thead><tr><th>{t('Hồ sơ','Record','档案')}</th><th>{t('Trạng thái','State','状态')}</th><th>{t('Bản hiện hành','Revision','版本')}</th><th>{t('Cập nhật','Updated','更新')}</th><th/></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><b>{tr(d.data.name,language)||t('Bản nháp chưa có tên','Untitled draft','未命名草稿')}</b><small>{d.id}</small></td><td><span className="workflow-badge">{optionText(d.state,language)}</span>{d.published&&<small>{t('Có bản công khai riêng','Public version retained','保留独立公开版本')}</small>}</td><td>{d.revision}</td><td>{d.updatedBy}</td><td><Link className="button" to={`/admin/${kind==='park'?'industrial-parks':'assets'}/${d.id}/edit`}>{t('Mở hồ sơ','Open record','打开档案')}</Link></td></tr>)}</tbody></table>{!rows.length&&<StatePanel title={t('Chưa có hồ sơ phù hợp','No matching records','暂无匹配档案')} text={t('Tạo bản nháp hoặc thay đổi từ khóa.','Create a draft or change your search.','创建草稿或调整关键词。')}/>}</div></div></Access>}
export function ContentEditor({kind}:{kind:ContentKind}){const {id}=useParams(),a=useAdmin(),{language}=useApp(),t=useText(),navigate=useNavigate();const record=a.store.drafts.find(d=>d.id===id&&d.kind===kind);const [data,setData]=useState<Content>(()=>structuredClone(record?.data||newContent(kind))),[revision,setRevision]=useState(record?.revision),[tab,setTab]=useState('identity'),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState(false),[preview,setPreview]=useState(false),[pendingTarget,setPendingTarget]=useState<string>();
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};const linkHandler=(e:MouseEvent)=>{const anchor=(e.target as HTMLElement).closest('a');if(dirty&&anchor?.getAttribute('href')?.startsWith('#/')){e.preventDefault();e.stopPropagation();setPendingTarget(anchor.getAttribute('href')!.slice(1));setConfirmation(true)}};window.addEventListener('beforeunload',handler);document.addEventListener('click',linkHandler,true);return()=>{window.removeEventListener('beforeunload',handler);document.removeEventListener('click',linkHandler,true)}},[dirty]);
  const errors=contentErrors(data),issues=publicationIssues(data,a.store.drafts);const change=(key:string,value:unknown)=>{setData({...data,[key]:value});setDirty(true);setMessage('')};
  const reload=()=>{if(record){setData(structuredClone(record.data));setRevision(record.revision)}setDirty(false);setMessage('')};
  const save=()=>{const r=a.save(data,revision);setMessage(r.ok?'saved':r.error||'validation');if(r.ok){setDirty(false);setRevision((revision||0)+1);if(!id)navigate(`/admin/${kind==='park'?'industrial-parks':'assets'}/${r.id}/edit`,{replace:true})}};
  const workflow=(action:'submit'|'approve'|'return'|'publish')=>{if(!record||dirty){setMessage('validation');return}const r=a.workflow(record.id,revision!,action,reason);setMessage(r.ok?'success':r.error||'validation');if(r.ok)setRevision(revision!+1)};
  const keys=kind==='asset'?['parkId','name','description','type','area','unit','transaction','priceMode','price','pricingBasis','availableFrom','powerMva','industries','image','imageApproved','featured']:parkGroups.find(g=>g[0]===tab)?.[4]||parkGroups[0][4];
  return <Access permission="P01"><div className="admin-page workflow-page"><div className="admin-title"><div><span>{record?.id||t('BẢN NHÁP MỚI','NEW DRAFT','新草稿')} · {optionText(record?.state||'draft',language)}</span><h1>{kind==='park'?t('Biên tập hồ sơ KCN','Edit industrial park','编辑园区档案'):t('Biên tập sản phẩm','Edit industrial asset','编辑工业地产')}</h1></div><div className="admin-actions"><button className="button" onClick={()=>dirty?setConfirmation(true):navigate(kind==='park'?'/admin/industrial-parks':'/admin/assets')}>{t('Quay lại','Back','返回')}</button>{(a.can('P02')||a.can('P08'))&&<button className="button primary" onClick={save}>{t('Lưu nháp','Save draft','保存草稿')}</button>}</div></div><AdminNotice/><Message code={message}/>{Object.keys(errors).length>0&&<div className="admin-message error" role="alert">{t('Trường cần kiểm tra: ','Fields to check: ','待检查字段：')}{Object.keys(errors).join(' · ')}</div>}{record&&record.revision!==revision&&<div className="admin-message error">{t('Bản mới đã thay đổi. Tải lại để rà soát; không ghi đè.','A newer revision exists. Reload to review; do not overwrite.','已有新版本，请重新加载审核，不能覆盖。')}<button className="button" onClick={reload}>{t('Tải lại','Reload','重新加载')}</button></div>}
    <div className="editor-layout">{kind==='park'&&<nav className="editor-nav">{parkGroups.map(g=><button key={g[0]} className={tab===g[0]?'active':''} onClick={()=>setTab(g[0])}>{g[language==='vi'?1:language==='en'?2:3]}</button>)}</nav>}<section className="admin-panel editor-fields"><h2>{kind==='park'?parkGroups.find(g=>g[0]===tab)?.[language==='vi'?1:language==='en'?2:3]:t('Thông tin sản phẩm','Asset information','地产信息')}</h2><p>{t('Bản nháp cho phép thiếu thông tin. Các giá trị đã nhập phải hợp lệ.','Drafts may be incomplete; entered values must be valid.','草稿可不完整，已填写数值必须有效。')}</p>{keys.map(key=><Field key={key} path={key} value={(data as any)[key]??(key==='contact'?blank(parks[0].contact):key==='coordinates'?{lat:null,lng:null}:key==='imageApproved'?false:'')} onChange={value=>change(key,value)} errors={errors} disabled={!a.can('P02')}/>)}<div className="admin-actions">{(a.can('P02')||a.can('P08'))&&<button className="button primary" onClick={save}>{t('Lưu nháp','Save draft','保存草稿')}</button>}<button className="button" onClick={()=>setPreview(!preview)}>{t('Xem trước dữ liệu','Preview data','预览数据')}</button></div></section></div>
    {preview&&<section className="admin-panel"><h2>{t('Xem trước bản nháp — chưa công bố','Draft preview — not public','草稿预览—尚未发布')}</h2><h3>{tr(data.name,language)||t('Chưa có tên','Untitled','未命名')}</h3><p>{tr(isPark(data)?data.summary:data.description,language)}</p><SafeImage src={isPark(data)?data.media.find(m=>m.approved)?.url:data.imageApproved?data.image:undefined} alt={tr(data.name,language)}/><p>{t('Giá trị không công bố được che trên Public.','Non-disclosed values are hidden on Public.','不公开的数值将在公开页面隐藏。')}</p></section>}
    <section className="admin-panel"><h2>{t('Checklist & rà soát công bố','Publication checklist & review','发布清单与审核')}</h2><p>{t('Không có phần trăm hoàn thiện. Bản công khai cũ giữ nguyên đến khi công bố bản đã duyệt.','No completeness percentage. The old public version remains until an approved revision is published.','不使用完成度百分比，已审核版本发布前保留原公开内容。')}</p><div className="checklist-tags">{issues.length?issues.map(i=><span key={i} className="admin-message error">{t('Cần bổ sung: ','Required: ','待补充：')}{labelFor(i,language)}</span>):<span className="admin-message success">{t('Đạt điều kiện dữ liệu','Data requirements met','数据符合要求')}</span>}</div><textarea aria-label={t('Lý do trả chỉnh sửa','Revision request reason','退回修改原因')} placeholder={t('Lý do trả chỉnh sửa','Revision request reason','退回修改原因')} value={reason} onChange={e=>setReason(e.target.value)}/><div className="admin-actions">{a.can('P04')&&record?.state==='draft'&&<button className="button" disabled={dirty} onClick={()=>workflow('submit')}>{t('Gửi duyệt','Submit for review','提交审核')}</button>}{a.can('P05')&&record?.state==='in_review'&&<><button className="button" disabled={dirty||!reason.trim()} onClick={()=>workflow('return')}>{t('Trả chỉnh sửa','Request changes','退回修改')}</button><button className="button primary" disabled={dirty||!!issues.length} onClick={()=>workflow('approve')}>{t('Duyệt nội dung','Approve','审核通过')}</button></>}{a.can('P06')&&record?.state==='approved'&&<button className="button primary" disabled={dirty||!!issues.length} onClick={()=>workflow('publish')}>{t('Công bố','Publish','发布')}</button>}</div>{a.store.audit.filter(x=>x.domain==='content'&&x.target===data.id).map(x=><details className="audit-item" key={x.id}><summary>{x.action} · {x.actor} · {new Date(x.at).toLocaleString()}</summary><p>{x.reason}</p><div className="diff-columns"><pre>{x.before}</pre><pre>{x.after}</pre></div></details>)}</section>
    {confirmation&&<Confirm title={t('Bỏ thay đổi chưa lưu?','Discard unsaved changes?','放弃未保存更改？')} onConfirm={()=>{setDirty(false);navigate(pendingTarget||(kind==='park'?'/admin/industrial-parks':'/admin/assets'))}} onCancel={()=>{setConfirmation(false);setPendingTarget(undefined)}}/>}
  </div></Access>;
}
