import type {Language} from '../types';
const options:Record<string,[string,string,string]>={
  draft:['Bản nháp','Draft','草稿'],in_review:['Chờ duyệt','In review','待审核'],approved:['Đã duyệt','Approved','已审核'],published:['Đã công bố','Published','已发布'],
  operational:['Đang hoạt động','Operational','运营中'],developing:['Đang phát triển','Developing','开发中'],planned:['Quy hoạch','Planned','规划中'],construction:['Đang xây dựng','Under construction','建设中'],
  North:['Miền Bắc','North','北部'],Central:['Miền Trung','Central','中部'],South:['Miền Nam','South','南部'],
  lease:['Cho thuê','Lease','出租'],sale:['Bán','Sale','出售'],industrial_land:['Đất công nghiệp','Industrial land','工业用地'],ready_built_factory:['Nhà xưởng xây sẵn','Ready-built factory','现成厂房'],warehouse:['Kho','Warehouse','仓库'],build_to_suit:['Xây theo yêu cầu','Build to suit','按需建设'],
  public:['Công khai','Public','公开'],not_disclosed:['Không công bố','Not disclosed','不公开'],not_available:['Chưa có thông tin','Not available','暂无资料'],admin_only:['Chỉ Admin','Admin only','仅管理员'],unverified:['Chưa xác minh','Unverified','未核验'],reviewed:['Đã rà soát','Reviewed','已审阅'],verified:['Đã xác minh','Verified','已核验'],
  electricity:['Điện','Electricity','电力'],water:['Cấp nước','Water supply','供水'],wastewater:['Xử lý nước thải','Wastewater','污水处理'],road:['Đường bộ','Road','公路'],telecom:['Viễn thông','Telecom','通信'],security:['An ninh','Security','安保'],drainage:['Thoát nước','Drainage','排水'],fire:['Phòng cháy','Fire protection','消防'],
  port:['Cảng biển','Port','港口'],airport:['Sân bay','Airport','机场'],rail:['Đường sắt','Railway','铁路'],city:['Trung tâm đô thị','City centre','市中心'],logistics:['Trung tâm logistics','Logistics hub','物流中心'],
  hero:['Ảnh chính','Hero image','主图'],gallery:['Thư viện ảnh','Gallery','图库'],site_photo:['Ảnh hiện trạng','Site photo','现场照片'],masterplan:['Quy hoạch','Masterplan','总平面图'],map:['Bản đồ','Map','地图'],video:['Video','Video','视频'],
  brochure:['Brochure','Brochure','宣传册'],presentation:['Bài giới thiệu','Presentation','介绍资料'],establishment_decision:['Quyết định thành lập','Establishment decision','设立决定'],enterprise_registration:['Đăng ký doanh nghiệp','Enterprise registration','企业登记'],legal_approval:['Phê duyệt pháp lý','Legal approval','法律批文'],
  specific:['Giá cụ thể','Specific price','具体价格'],negotiable:['Thỏa thuận','Negotiable','面议'],create:['Tạo mới','Create','新建'],update:['Cập nhật','Update','更新'],created:['Đã tạo nháp','Draft created','已创建草稿'],updated:['Đã cập nhật nháp','Draft updated','已更新草稿'],failed:['Thất bại','Failed','失败'],preview:['Chờ rà soát','Awaiting review','等待审阅'],complete:['Đã hoàn tất','Completed','已完成'],
};
export const optionText=(value:string,language:Language)=>options[value]?.[language==='vi'?0:language==='en'?1:2]||value;
export const permissionNames:Record<string,[string,string,string]>={P01:['Xem nháp','View drafts','查看草稿'],P02:['Soạn nháp','Edit drafts','编辑草稿'],P03:['Nhập hàng loạt','Batch import','批量导入'],P04:['Gửi duyệt','Submit review','提交审核'],P05:['Duyệt / trả chỉnh sửa','Review / request changes','审核 / 退回'],P06:['Công bố','Publish','发布'],P07:['Xem tài liệu hạn chế','View restricted documents','查看受限文档'],P08:['Xác minh / quyền tài liệu','Verification / document access','核验 / 文档权限'],P09:['Xem Connection','View connections','查看对接'],P10:['Xử lý Connection','Process connections','处理对接'],P11:['Xem báo cáo','View reports','查看报告'],P12:['Xem người dùng','View users','查看用户'],P13:['Quản lý lời mời','Manage invitations','管理邀请'],P14:['Quản lý quyền truy cập','Manage access','管理访问权限'],P15:['Xem lịch sử quyền','View access audit','查看权限日志'],P16:['Xem lịch sử nội dung','View content history','查看内容历史'],P17:['Xem lịch sử Connection','View connection history','查看对接历史'],P18:['Xuất báo cáo Expo','Export Expo report','导出展会报告']};
