import {useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import ExcelJS from 'exceljs';
import {useApp,tr} from '../AppContext';
import {useAdmin} from './AdminContext';
import {Access,AdminNotice,Message,useText} from './ui';
import {downloadWorkbook} from './workbooks';
import {StatePanel} from '../EmptyStates';
export function createExpoWorkbook(input:{id:string;name:string;from:string;to:string;rows:[string,string|number][];exhibitors:{id:string;name:string;logo:string;status:string}[]}){const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Expo Performance');ws.addRows([['Expo ID',input.id],['Expo',input.name],['From',input.from],['To',input.to],['Timezone','Asia/Ho_Chi_Minh'],['Source','VIG demo — not connected to TradeXpo'],...input.rows]);ws.columns=[{width:40},{width:70}];const ex=wb.addWorksheet('Approved Exhibitors');ex.addRow(['ID','Name','Logo','Public approval status']);input.exhibitors.forEach(e=>ex.addRow([e.id,e.name,e.logo,e.status]));ex.columns.forEach(c=>c.width=28);return wb;}
export function ExpoReport(){const app=useApp(),a=useAdmin(),t=useText(),{id}=useParams(),expo=app.expos.find(e=>e.id===id);const today=new Date().toISOString().slice(0,10),week=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const [from,setFrom]=useState(week),[to,setTo]=useState(today),[applied,setApplied]=useState({from:week,to:today}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[simulation,setSimulation]=useState('normal');const ref=useRef({can:a.can,simulation});ref.current={can:a.can,simulation};const exporting=useRef(false);
  if(!expo)return <StatePanel title={t('Không có báo cáo','Report unavailable','报告不可用')} text={t('Expo không tồn tại trong nguồn demo.','Expo does not exist in demo source.','演示数据源中不存在此展会。')}/>;
  const missing=t('Chưa có nguồn tương thích','Compatible source unavailable','暂无兼容数据源');
  const rows:[string,string|number][]=[['Connection',missing],['Inbound',missing],['Outbound',missing],[t('Đang xử lý','In progress','处理中'),missing],[t('Kết nối thành công','Successful connections','成功对接'),missing],[t('Tỷ lệ thành công','Success rate','成功率'),missing],[t('Lượt xem trong kỳ','Views in period','期间浏览量'),missing],[t('Đơn vị (snapshot demo)','Exhibitors (demo snapshot)','参展商（演示快照）'),expo.exhibitors],[t('Sản phẩm (snapshot demo)','Products (demo snapshot)','产品（演示快照）'),expo.analytics.products],[t('Cập nhật nguồn','Source updated','来源更新'),expo.analytics.updatedAt]];
  const exportFile=async()=>{if(exporting.current)return;if(!a.can('P18')||simulation==='revoked'){setMessage('permission');return;}exporting.current=true;setBusy(true);setMessage('');try{await new Promise(resolve=>setTimeout(resolve,350));if(!ref.current.can('P18')||ref.current.simulation==='revoked'){setMessage('permission');return}if(ref.current.simulation==='failure')throw new Error('demo');await downloadWorkbook(createExpoWorkbook({id:expo.id,name:tr(expo.title,app.language),...applied,rows,exhibitors:[]}),`VIG-${expo.id}-${applied.from}-${applied.to}.xlsx`);setMessage('success')}catch{setMessage('validation')}finally{exporting.current=false;setBusy(false)}};
  return <Access permission="P11"><div className="admin-page workflow-page"><Link to="/admin/expos">← {t('Danh sách Expo','Expo list','展会列表')}</Link><div className="admin-title"><div><span>TRADEXPO • VIG</span><h1>{tr(expo.title,app.language)}</h1><p>{t('Báo cáo và xuất dữ liệu theo từng Expo','Per-Expo reporting and export','单展会报告与导出')}</p></div>{a.can('P18')&&<button className="button primary" disabled={busy||simulation==='revoked'} onClick={exportFile}>{busy?t('Đang tạo file…','Preparing file…','正在生成…'):t('Xuất báo cáo Excel','Export Excel report','导出Excel报告')}</button>}</div><AdminNotice/><p className="admin-demo-notice">{t('Phạm vi tổ chức VIG được mô phỏng. Chưa xác nhận nguồn Connection có định danh từ TradeXpo; không đổi Matching/RFQ + Chat thành Connection.','VIG organization scope is simulated. Identified Connection data from TradeXpo is not confirmed; Matching/RFQ + Chat is not converted into Connection.','VIG组织范围为演示，尚未确认TradeXpo提供可追溯对接数据，不将匹配/RFQ和聊天转为对接数。')}</p><div className="admin-panel"><form className="admin-actions" onSubmit={e=>{e.preventDefault();if(!from||!to||from>to||to>today){setMessage('validation');return}setApplied({from,to});setMessage('')}}><label>{t('Từ ngày','From','开始日期')}<input type="date" required value={from} max={today} onChange={e=>setFrom(e.target.value)}/></label><label>{t('Đến ngày','To','结束日期')}<input type="date" required value={to} max={today} onChange={e=>setTo(e.target.value)}/></label><button className="button">{t('Áp dụng','Apply','应用')}</button></form><p>Asia/Ho_Chi_Minh · {applied.from} → {applied.to}</p><label>{t('Kiểm tra trạng thái xuất (demo)','Export state preview (demo)','导出状态预览（演示）')}<select value={simulation} onChange={e=>setSimulation(e.target.value)}><option value="normal">{t('Bình thường','Normal','正常')}</option><option value="failure">{t('Lỗi tạo file','Generation failure','生成失败')}</option><option value="revoked">{t('Thu hồi phạm vi nguồn','Source scope revoked','数据范围已撤销')}</option></select></label></div><Message code={message}/>{simulation==='revoked'?<StatePanel kind="forbidden" title={t('Phạm vi báo cáo đã bị thu hồi','Report scope revoked','报告范围已撤销')} text={t('Không hiển thị hoặc xuất dữ liệu ngoài quyền.','Out-of-scope data cannot be displayed or exported.','不能显示或导出权限范围外的数据。')}/>:<><div className="report-facts">{rows.map(([label,value])=><article className="admin-panel" key={label}><small>{label}</small><h3>{value}</h3></article>)}</div><section className="admin-panel"><h2>{t('Đơn vị đã duyệt','Approved exhibitors','已审核参展商')}</h2><StatePanel title={t('Chưa có danh sách nguồn','Source list unavailable','暂无来源列表')} text={t('Sheet Approved Exhibitors vẫn có header, không tạo dòng giả hoặc xuất thông tin liên hệ riêng tư.','The Approved Exhibitors sheet retains headers; no fake rows or private contact data.','Approved Exhibitors工作表保留表头，不生成虚假行或导出私人联系信息。')}/></section></>}</div></Access>;
}
