import {useState} from 'react';
import {useAdmin} from './AdminContext';
import {useApp} from '../AppContext';
import {permissionNames} from './copy';
import {Access,AdminNotice,Message,RoleName,useText} from './ui';
import {rolePermissions,type AdminRole} from './model';

export function PermissionMatrix(){
  const a=useAdmin(),{language}=useApp(),t=useText();
  const [draft,setDraft]=useState(()=>structuredClone(a.store.matrix)),[revision,setRevision]=useState(a.store.matrixRevision),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState('');
  const editable=a.current?.role==='SA'&&a.can('P21'),dirty=JSON.stringify(draft)!==JSON.stringify(a.store.matrix),stale=revision!==a.store.matrixRevision;
  const roles=(['SA','ADMIN','OPERATOR'] as AdminRole[]).filter(r=>filter==='all'||r===filter);
  const groups=[{label:t('Nội dung & dữ liệu','Content & data','内容与数据'),ids:['P01','P02','P03','P04','P05','P06','P07','P08','P16','P22','P23']},{label:t('Kết nối & báo cáo','Connections & reports','对接与报告'),ids:['P09','P10','P11','P17','P18']},{label:t('Người dùng & quyền','Users & access','用户与权限'),ids:['P12','P13','P14','P15','P19','P20','P21']}];
  const label=(p:string)=>permissionNames[p]?.[language==='vi'?0:language==='en'?1:2]||p;
  const reset=()=>{setDraft(structuredClone(a.store.matrix));setRevision(a.store.matrixRevision);setMessage('');setNote('')};
  return <Access permission="P20"><div className="admin-page workflow-page"><div className="admin-title"><div><span>VIG ADMIN</span><h1>{t('Ma trận quyền','Permission matrix','权限矩阵')}</h1></div><span className="workflow-badge">{editable?t('Chỉ Super Admin được sửa','Super Admin editing','仅超级管理员可编辑'):t('Chỉ xem','Read only','只读')}</span></div><AdminNotice/><p>{t('Mỗi người có một vai trò. Thay đổi áp dụng cho tất cả người dùng của vai trò sau khi lưu.','Each person has one role. Saved changes apply to every user assigned that role.','每人仅有一个角色，保存后更改将应用于该角色的所有用户。')}</p><div className="admin-filter"><label>{t('Vai trò','Role','角色')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('Tất cả','All roles','全部角色')}</option><option value="SA">Super Admin</option><option value="ADMIN">Admin</option><option value="OPERATOR">Operator</option></select></label><label>{t('Tìm quyền','Search permissions','搜索权限')}<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div><Message code={message}/>{stale&&<Message code="stale"/>}
  {groups.map(g=>{const ids=g.ids.filter(p=>(label(p)+' '+p).toLowerCase().includes(query.toLowerCase()));return !!ids.length&&<section className="admin-panel matrix-group" key={g.label}><h2>{g.label}</h2><div className="table-scroll"><table className="workflow-table permission-table"><thead><tr><th>{t('Quyền','Permission','权限')}</th>{roles.map(r=><th key={r}><RoleName role={r}/></th>)}</tr></thead><tbody>{ids.map(p=><tr key={p}><td><b>{label(p)}</b><small>{p}</small></td>{roles.map(r=><td key={r}><input type="checkbox" aria-label={`${r} ${p}`} checked={draft[r].includes(p)} disabled={!editable||r==='SA'||p==='P21'} onChange={e=>{setDraft({...draft,[r]:e.target.checked?[...draft[r],p]:draft[r].filter(x=>x!==p)});setMessage('')}}/></td>)}</tr>)}</tbody></table></div></section>})}
  {!groups.some(g=>g.ids.some(p=>(label(p)+' '+p).toLowerCase().includes(query.toLowerCase())))&&<section className="admin-panel"><p>{t('Không có quyền phù hợp.','No matching permissions.','没有匹配权限。')}</p><button className="button" onClick={()=>setQuery('')}>{t('Xóa tìm kiếm','Clear search','清除搜索')}</button></section>}
  {editable&&<section className="admin-panel"><label>{t('Ghi chú thay đổi (tùy chọn)','Change note (optional)','更改备注（选填）')}<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><p>{dirty?t('Có thay đổi chưa lưu','Unsaved changes','有未保存的更改'):t('Không có thay đổi','No unsaved changes','无未保存更改')}</p><div className="admin-actions"><button className="button primary" disabled={!dirty||stale} onClick={()=>{const r=a.configure(draft,revision,note);setMessage(r.ok?'success':r.error||'validation');if(r.ok)setRevision(revision+1)}}>{t('Lưu thay đổi','Save changes','保存更改')}</button><button className="button" onClick={reset}>{stale?t('Tải lại','Reload','重新加载'):t('Hủy thay đổi','Cancel changes','取消更改')}</button></div></section>}
  </div></Access>
}
