import {permissionNames} from './copy';
import type {ReactNode} from 'react';
import {useApp} from '../AppContext';
import {emptyCopy,StatePanel} from '../EmptyStates';
import {useAdmin} from './AdminContext';
import {firstAdminPage,permissions,type AdminRole,type AdminUser} from './model';
import {Link} from 'react-router-dom';
export const useText=()=>{const {language}=useApp();return (vi:string,en:string,zh:string)=>emptyCopy(language,vi,en,zh)};
export function AdminLanguage(){const {language,setLanguage}=useApp();return <label className="language-select"><span className="language-flag" aria-hidden="true">{language==='vi'?'🇻🇳':language==='zh'?'🇨🇳':'🇬🇧'}</span><select aria-label="Language" value={language} onChange={e=>setLanguage(e.target.value as 'vi'|'en'|'zh')}><option value="vi">Tiếng Việt</option><option value="en">English</option><option value="zh">中文</option></select></label>}
export function AdminNotice(){const t=useText();return <p className="admin-demo-notice">{t('Phiên bản demo VIG • Dữ liệu trong bộ nhớ, khôi phục khi tải lại trang. Không gửi email thật.','VIG demo • In-memory data resets on refresh. No real emails.','VIG演示 • 刷新后恢复初始数据，不发送真实邮件。')}</p>}
export function Access({permission,children}:{permission:string;children:ReactNode}){const a=useAdmin(),t=useText();return a.can(permission)?<>{children}</>:<div className="admin-page"><StatePanel kind="forbidden" title={t('Bạn chưa có quyền truy cập','Access not permitted','无访问权限')} text={t('Liên hệ Super Admin để được kiểm tra quyền.','Contact your Super Admin to review access.','请联系超级管理员审核权限。')} action={<Link className="button" to={firstAdminPage(a.current,a.store.matrix)}>{t('Về trang được phép','Return to permitted page','返回可访问页面')}</Link>}/></div>}
export function RoleName({role}:{role:AdminRole}){const t=useText();return <>{({SA:t('Super Admin','Super Admin','超级管理员'),ADMIN:t('Admin','Admin','管理员'),OPERATOR:t('Operator','Operator','运营员')})[role]}</>}
export function Roles({value,onChange}:{value?:AdminRole|null;onChange?:(r:AdminRole)=>void}){const t=useText();return <label className="role-select">{t('Vai trò','Role','角色')}<select value={value||''} disabled={!onChange} onChange={e=>onChange?.(e.target.value as AdminRole)}><option value="" disabled>{t('Chọn một vai trò','Select one role','选择一个角色')}</option>{(value==='SA'?['SA']:['ADMIN','OPERATOR']).map(r=><option key={r} value={r}>{r==='ADMIN'?t('Admin','Admin','管理员'):r==='OPERATOR'?t('Operator','Operator','运营员'):'Super Admin'}</option>)}</select></label>}
export function PermissionPreview({role,user}:{role?:AdminRole;user?:AdminUser}){const t=useText(),a=useAdmin(),{language}=useApp();const items=user?permissions(user,a.store.matrix):role?a.store.matrix[role]:[];return <div className="permission-preview"><b>{user?t('Quyền đang có hiệu lực','Effective permissions','当前有效权限'):t('Quyền được cấu hình cho vai trò','Configured role permissions','角色配置权限')}</b><ul>{items.map(p=><li key={p}>{permissionNames[p]?.[language==='vi'?0:language==='en'?1:2]||p}</li>)}</ul>{!items.length&&<p>{t('Không có quyền hiệu lực / chưa chọn vai trò.','No permissions / no role selected.','无权限或尚未选择角色。')}</p>}</div>}
export function Message({code}:{code?:string}){const t=useText();if(!code)return null;const copy:Record<string,string>={credentials:t('Tên đăng nhập hoặc mật khẩu không đúng.','Incorrect username or password.','用户名或密码错误。'),dependencies:t('Bật các quyền xem liên quan trước khi cấp quyền thao tác.','Enable the required view permissions before granting actions.','请先启用相关查看权限。'),permission:t('Không có quyền thao tác.','Permission denied.','无操作权限。'),stale:t('Bản dữ liệu đã thay đổi. Tải lại trước khi tiếp tục.','The record changed. Reload before continuing.','数据已变更，请重新加载。'),roles:t('Chọn một vai trò hợp lệ.','Select exactly one valid role.','请选择一个有效角色。'),duplicate:t('Đã có lời mời đang chờ cho email này.','A pending invitation already exists.','此邮箱已有待接受邀请。'),existing:t('Tài khoản đã hoạt động. Chuyển sang quản lý Role.','Account is active. Manage its roles instead.','账户已激活，请管理其角色。'),validation:t('Kiểm tra các trường đã nhập.','Check the entered fields.','请检查输入字段。'),publication:t('Chưa đạt điều kiện công bố. Xem checklist.','Publication requirements are not met. See checklist.','未满足发布要求，请检查清单。'),reason:t('Vui lòng nhập lý do.','A reason is required.','请填写原因。'),password:t('Mật khẩu từ 8 ký tự, có hoa/thường/số/ký tự đặc biệt; xác nhận phải trùng.','Use 8+ characters with upper/lowercase, number and symbol; confirmation must match.','密码至少8位，含大小写字母、数字和符号，两次输入必须一致。'),invalidInvite:t('Liên kết không hợp lệ, hết hạn, đã dùng hoặc bị thu hồi.','Invitation is invalid, expired, used or revoked.','邀请无效、已过期、已使用或已撤回。'),accountMismatch:t('Bạn đang dùng tài khoản khác. Chuyển về Public trước khi tiếp nhận lời mời.','You are using another account. Return to Public before accepting.','您正在使用其他账户，请先退出管理门户。'),disabled:t('Tài khoản hoặc quyền truy cập chưa đủ điều kiện.','Account or access is not eligible.','账户或访问权限不符合条件。'),protected:t('Không được thay đổi Super Admin qua Portal.','Super Admin cannot be modified in the Portal.','不能在门户修改超级管理员。'),parkId:t('KCN liên kết không hợp lệ.','Linked park is invalid.','关联园区无效。'),slug:t('Đường dẫn đã được sử dụng.','Slug is already in use.','路径已被使用。'),dependency:t('Chọn cả KCN mới được sản phẩm tham chiếu.','Select the new parent park as well.','请同时选择关联的新园区。'),saved:t('Đã lưu bản nháp. Bản công khai chưa thay đổi.','Draft saved. Public content is unchanged.','草稿已保存，公开内容未改变。'),success:t('Thao tác thành công trong demo.','Action completed in the demo.','演示操作成功。')};return <p role="status" className={`admin-message ${['saved','success'].includes(code)?'success':'error'}`}>{copy[code]||t('Không thể thực hiện. Kiểm tra điều kiện và thử lại.','Unable to proceed. Check conditions and retry.','无法继续，请检查条件后重试。')}</p>}
export function Confirm({title,children,onConfirm,onCancel}:{title:string;children?:ReactNode;onConfirm:()=>void;onCancel:()=>void}){const t=useText();return <div className="admin-confirm" role="dialog" aria-modal="true" aria-label={title}><div><h2>{title}</h2>{children}<div className="admin-actions"><button className="button" onClick={onCancel}>{t('Hủy','Cancel','取消')}</button><button className="button primary" onClick={onConfirm}>{t('Xác nhận','Confirm','确认')}</button></div></div></div>}
