import {useState,useEffect} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useApp} from '../AppContext';
import {useAdmin} from './AdminContext';
import {AdminNotice,Roles,RoleName,PermissionPreview,Message,Confirm,useText,Access} from './ui';
import {firstAdminPage,inviteStatus,type AdminRole,type AdminUser} from './model';
import {StatePanel} from '../EmptyStates';

export function DemoSession(){const a=useAdmin(),t=useText(),navigate=useNavigate();return <label className="demo-session">{t('Tài khoản demo','Demo account','演示账户')}<select value={a.current?.id||''} onChange={e=>{const u=a.store.users.find(x=>x.id===e.target.value);a.selectUser(e.target.value);navigate(firstAdminPage(u))}}>{a.store.users.filter(u=>u.account==='active').map(u=><option key={u.id} value={u.id}>{u.name} ({u.roles.join('+')||'—'})</option>)}</select></label>}
export function UsersPage(){const a=useAdmin(),t=useText();const [tab,setTab]=useState('users'),[q,setQ]=useState(''),[role,setRole]=useState('all'),[status,setStatus]=useState('all'),[selected,setSelected]=useState<string>(),[inviteForm,setInviteForm]=useState(false),[resend,setResend]=useState<string>(),[message,setMessage]=useState(''),[confirm,setConfirm]=useState<{id:string;action:string}>();
  const [roles,setRoles]=useState<AdminRole[]>([]),[revision,setRevision]=useState(0),[reason,setReason]=useState('');
  const user=a.store.users.find(u=>u.id===selected);
  const statusText=(s:string)=>({active:t('Hoạt động','Active','有效'),pending:t('Chờ kích hoạt','Pending','待激活'),suspended:t('Tạm khóa','Suspended','已暂停'),removed:t('Đã gỡ','Removed','已移除'),invited:t('Được mời','Invited','已邀请'),disabled:t('Vô hiệu','Disabled','已禁用'),expired:t('Hết hạn','Expired','已过期'),accepted:t('Đã chấp nhận','Accepted','已接受'),revoked:t('Đã thu hồi','Revoked','已撤回')})[s]||s;
  const open=(u:AdminUser)=>{setSelected(u.id);setRoles([...u.roles]);setRevision(u.revision);setMessage('')};
  const list=a.store.users.filter(u=>(u.name+' '+u.email).toLowerCase().includes(q.toLowerCase())&&(role==='all'||u.roles.includes(role as AdminRole))&&(status==='all'||u.access===status));
  const invitations=a.store.invites.filter(i=>{const u=a.store.users.find(u=>u.id===i.userId);return (u?.name+' '+u?.email).toLowerCase().includes(q.toLowerCase())&&(role==='all'||i.roles.includes(role as AdminRole))&&(status==='all'||inviteStatus(i)===status)});
  const act=()=>{if(!confirm)return;const result=confirm.action==='revoke'?a.revoke(confirm.id):confirm.action==='roles'?a.updateUser(confirm.id,revision,roles,user?.access==='removed'?'active':undefined,reason):a.updateUser(confirm.id,revision,undefined,confirm.action as AdminUser['access'],reason);setMessage(result.ok?'success':result.error||'validation');setConfirm(undefined);if(result.ok){setSelected(undefined);setReason('')}};
  return <Access permission="P12"><div className="admin-page workflow-page"><div className="admin-title"><div><span>VIG ADMIN</span><h1>{t('Người dùng và phân quyền','Users & permissions','用户与权限')}</h1></div>{a.can('P13')&&<button className="button primary" onClick={()=>{setResend(undefined);setInviteForm(true)}}>{t('Mời người dùng','Invite user','邀请用户')}</button>}</div><AdminNotice/><div className="workflow-tabs">{[['users',t('Người dùng','Users','用户')],['invites',t('Lời mời','Invitations','邀请')],['audit',t('Lịch sử quyền','Access audit','权限日志')]].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setStatus('all');setSelected(undefined)}}>{label}</button>)}</div>
    {tab!=='audit'&&<div className="admin-filter"><input aria-label={t('Tìm tên hoặc email','Search name or email','搜索姓名或邮箱')} placeholder={t('Tìm tên hoặc email','Search name or email','搜索姓名或邮箱')} value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Role" value={role} onChange={e=>setRole(e.target.value)}><option value="all">{t('Tất cả Role','All roles','全部角色')}</option>{(['SA','NL','DC','VH','BC'] as AdminRole[]).map(r=><option key={r} value={r}>{r}</option>)}</select><select aria-label={t('Trạng thái','Status','状态')} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('Tất cả trạng thái','All statuses','全部状态')}</option>{(tab==='users'?['active','pending','suspended','removed']:['pending','expired','accepted','revoked']).map(s=><option key={s} value={s}>{statusText(s)}</option>)}</select></div>}
    <Message code={message}/>
    {tab==='users'&&<div className="admin-panel table-scroll"><table className="workflow-table"><thead><tr><th>{t('Người dùng','User','用户')}</th><th>Role</th><th>{t('Tài khoản','Account','账户')}</th><th>{t('Truy cập VIG','VIG access','VIG访问')}</th><th/></tr></thead><tbody>{list.map(u=><tr key={u.id}><td><b>{u.name}</b><small>{u.email}</small></td><td>{u.roles.map(r=><span className="workflow-badge" key={r}><RoleName role={r}/></span>)}</td><td>{statusText(u.account)}</td><td>{statusText(u.access)}</td><td><button className="button" onClick={()=>open(u)}>{t('Chi tiết','Details','详情')}</button></td></tr>)}</tbody></table>{!list.length&&<StatePanel title={t('Không có người dùng phù hợp','No matching users','没有匹配用户')} text={t('Thử thay đổi bộ lọc.','Try changing filters.','请调整筛选条件。')} action={<button className="button" onClick={()=>{setQ('');setRole('all');setStatus('all')}}>{t('Xóa bộ lọc','Clear filters','清除筛选')}</button>}/>}</div>}
    {tab==='invites'&&<div className="admin-panel table-scroll"><table className="workflow-table"><thead><tr><th>{t('Người nhận','Recipient','收件人')}</th><th>Role</th><th>{t('Lời mời / Email','Invitation / Email','邀请 / 邮件')}</th><th>{t('Hết hạn','Expires','到期')}</th><th/></tr></thead><tbody>{invitations.map(i=>{const u=a.store.users.find(u=>u.id===i.userId)!;const s=inviteStatus(i);return <tr key={i.id}><td><b>{u.name}</b><small>{u.email}</small><small>{i.id}</small></td><td>{i.roles.map(r=><span className="workflow-badge" key={r}><RoleName role={r}/></span>)}</td><td>{statusText(s)}<small>{i.delivery==='failed'?t('Gửi thất bại (mẫu)','Delivery failed (sample)','发送失败（示例）'):t('Email chưa xác nhận — không gửi thật','Email unconfirmed — not sent','邮件未确认—未实际发送')}</small></td><td>{new Date(i.expiresAt).toLocaleString()}</td><td><div className="admin-actions">{s==='pending'&&<><button className="button" onClick={()=>setConfirm({id:i.id,action:'revoke'})}>{t('Thu hồi','Revoke','撤回')}</button><Link className="button" to={'/accept-invitation/'+i.token}>{t('Xem link demo','Open demo link','打开演示链接')}</Link></>}{s==='expired'&&<button className="button" onClick={()=>{setResend(i.id);setInviteForm(true)}}>{t('Gửi lại','Resend','重新邀请')}</button>}</div></td></tr>})}</tbody></table>{!invitations.length&&<StatePanel title={t('Chưa có lời mời phù hợp','No matching invitations','暂无匹配邀请')} text={t('Mời người dùng hoặc thay đổi bộ lọc.','Invite a user or change filters.','邀请用户或调整筛选。')}/>}</div>}
    {tab==='audit'&&<Access permission="P15"><div className="admin-panel"><h2>{t('Lịch sử quản lý quyền','Access management history','权限管理历史')}</h2>{!a.store.audit.filter(x=>x.domain==='users').length?<StatePanel title={t('Chưa có hoạt động','No activity yet','暂无操作')} text={t('Các thao tác mời và quản lý quyền sẽ được ghi tại đây.','Invitation and access actions appear here.','邀请和权限操作将记录在此。')}/>:a.store.audit.filter(x=>x.domain==='users').map(x=><details className="audit-item" key={x.id}><summary><b>{x.action}</b> · {a.store.users.find(u=>u.id===x.target)?.name||x.target}<small>{x.actor} · {new Date(x.at).toLocaleString()}</small></summary><div className="diff-columns"><pre>{x.before}</pre><pre>{x.after}</pre></div>{x.reason&&<p>{x.reason}</p>}</details>)}</div></Access>}
    {user&&tab==='users'&&<section className="admin-panel"><div className="admin-title"><h2>{user.name}</h2><button className="button" onClick={()=>setSelected(undefined)}>{t('Đóng','Close','关闭')}</button></div><p>{user.email} · {user.phone||t('Không có điện thoại','No phone','无电话')}</p><p>{statusText(user.account)} / {statusText(user.access)}</p>{user.roles.includes('SA')?<p>{t('Super Admin được khởi tạo từ Backend. Không chỉnh qua Portal.','Super Admin is provisioned by the backend and cannot be edited here.','超级管理员由后台创建，不能在门户修改。')}</p>:<><Roles value={roles} onChange={user.account==='active'?setRoles:undefined}/><div className="diff-columns"><PermissionPreview roles={user.roles}/><PermissionPreview roles={roles}/></div><div className="admin-actions">{user.account==='active'&&<button className="button primary" disabled={!roles.length} onClick={()=>setConfirm({id:user.id,action:'roles'})}>{t('Lưu Role','Save roles','保存角色')}</button>}{user.access==='active'&&<button className="button" onClick={()=>setConfirm({id:user.id,action:'suspended'})}>{t('Tạm khóa truy cập','Suspend access','暂停访问')}</button>}{user.access==='suspended'&&<button className="button" onClick={()=>setConfirm({id:user.id,action:'active'})}>{t('Khôi phục truy cập','Restore access','恢复访问')}</button>}{['active','suspended'].includes(user.access)&&<button className="button danger" onClick={()=>setConfirm({id:user.id,action:'removed'})}>{t('Gỡ quyền Admin','Remove Admin access','移除管理权限')}</button>}<button className="button" onClick={()=>open(user)}>{t('Tải lại bản hiện hành','Reload current version','重新加载当前版本')}</button></div></>}</section>}
    {inviteForm&&<InviteForm resend={resend} onClose={()=>setInviteForm(false)} onCreated={()=>{setInviteForm(false);setTab('invites');setMessage('success')}} onExisting={id=>{setInviteForm(false);setTab('users');open(a.store.users.find(u=>u.id===id)!);setMessage('existing')}}/>}
    {confirm&&<Confirm title={t('Xác nhận thay đổi','Confirm change','确认更改')} onCancel={()=>setConfirm(undefined)} onConfirm={act}><p>{t('Chỉ ảnh hưởng truy cập VIG Admin, không xóa tài khoản Arobid.','Only VIG Admin access is affected; the Arobid account is not deleted.','仅影响VIG管理访问，不删除Arobid账户。')}</p><label>{t('Ghi chú','Note','备注')}<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></Confirm>}
  </div></Access>;
}
function InviteForm({resend,onClose,onCreated,onExisting}:{resend?:string;onClose:()=>void;onCreated:()=>void;onExisting:(id:string)=>void}){const a=useAdmin(),t=useText();const old=a.store.invites.find(i=>i.id===resend),user=a.store.users.find(u=>u.id===old?.userId);const [name,setName]=useState(user?.name||''),[email,setEmail]=useState(user?.email||''),[phone,setPhone]=useState(user?.phone||''),[roles,setRoles]=useState<AdminRole[]>(old?.roles||[]),[error,setError]=useState('');return <div className="admin-confirm" role="dialog" aria-modal="true" aria-label={t('Mời người dùng','Invite user','邀请用户')}><form onSubmit={e=>{e.preventDefault();const r=a.invite({name,email,phone,roles},resend);if(r.ok)onCreated();else if(r.error==='existing'&&r.id)onExisting(r.id);else setError(r.error||'validation')}}><h2>{t('Mời người dùng','Invite user','邀请用户')}</h2><p>VIG Admin · {t('Thời hạn 72 giờ từ khi tạo','Expires 72 hours after creation','创建后72小时到期')}</p><Message code={error}/><div className="form-grid"><label>{t('Họ tên','Full name','姓名')}<input required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('Điện thoại (tùy chọn)','Phone (optional)','电话（选填）')}<input value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><Roles value={roles} onChange={setRoles}/><PermissionPreview roles={roles}/><p>{t('Lời mời mô phỏng, không gửi email thật.','Simulated invitation; no real email is sent.','演示邀请，不发送真实邮件。')}</p><div className="admin-actions"><button type="button" className="button" onClick={onClose}>{t('Hủy','Cancel','取消')}</button><button className="button primary" disabled={!roles.length}>{t('Tạo lời mời','Create invitation','创建邀请')}</button></div></form></div>}
export function AcceptInvitation(){const a=useAdmin(),app=useApp(),t=useText(),{token}=useParams(),navigate=useNavigate();const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[accepted,setAccepted]=useState(false);const i=a.store.invites.find(i=>i.token===token),u=a.store.users.find(u=>u.id===i?.userId);const [clock,setClock]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);const valid=i&&u&&inviteStatus(i,clock)==='pending'&&u.account==='invited';return <main className="invitation-page"><section className="admin-panel"><span className="brand-mark">VIG</span><h1>{t('Tiếp nhận lời mời VIG Admin','Accept VIG Admin invitation','接受VIG管理邀请')}</h1><AdminNotice/>{accepted?<><Message code="success"/><button className="button primary" onClick={()=>navigate(firstAdminPage(a.current))}>{t('Vào trang được phép','Continue to Admin','进入可访问页面')}</button></>:!valid?<Message code="invalidInvite"/>:app.role==='admin'&&a.current?.email!==u.email?<><Message code="accountMismatch"/><button className="button" onClick={()=>app.setRole('public')}>{t('Chuyển sang người nhận (demo)','Switch to recipient (demo)','切换为收件人（演示）')}</button></>:<form onSubmit={e=>{e.preventDefault();const r=a.accept(token!,password,confirm);setPassword('');setConfirm('');if(r.ok)setAccepted(true);else setError(r.error||'validation')}}><p>{u.email} · VIG Admin</p><Roles value={i.roles}/><PermissionPreview roles={i.roles}/><p>{t('Hết hạn','Expires','到期')}: {new Date(i.expiresAt).toLocaleString()}</p><Message code={error}/><label>{t('Mật khẩu','Password','密码')}<input required type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{t('Xác nhận mật khẩu','Confirm password','确认密码')}<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p>{t('Tối thiểu 8 ký tự, có chữ hoa, chữ thường, số và ký tự đặc biệt. Không lưu mật khẩu trong demo.','8+ characters with upper/lowercase, number and symbol. Passwords are not stored in this demo.','至少8位，含大小写字母、数字和符号，演示不保存密码。')}</p><button className="button primary">{t('Kích hoạt','Activate','激活')}</button></form>}<Link to="/home">{t('Về trang chủ','Home','返回首页')}</Link></section></main>}
