import {useState,useEffect} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useApp} from './AppContext';
import {emptyCopy} from './EmptyStates';
import {translateToChinese} from './i18n';
const industryLabel=(value:string,language:string)=>language==='zh'?translateToChinese(value):value;
import type {IndustrialParkProfile,IndustrialAsset} from './types';
export function matchesParkFilters(p:IndustrialParkProfile,s:URLSearchParams){
 const min=Number(s.get('minArea')||0),max=Number(s.get('maxArea')||Infinity),area=p.totalArea.disclosureStatus==='public'&&p.totalArea.value!=null?p.totalArea.value*(p.totalArea.unit==='ha'?10000:1):null;
 return (!s.get('province')||s.get('province')===p.province)&&(!(min||max<Infinity)||area!=null&&area>=min&&area<=max)&&(!s.has('available')||p.availability.some(a=>a.available.disclosureStatus==='public'&&Number(a.available.value)>0))&&s.getAll('utility').every(key=>p.utilities.some(u=>u.key===key&&u.capacity.disclosureStatus==='public'&&u.capacity.value!=null))&&s.getAll('connection').every(type=>p.connectivity.some(c=>c.type===type&&c.status==='operational'));
}
export function matchesAssetFilters(a:IndustrialAsset,p:IndustrialParkProfile,s:URLSearchParams){
 const min=Number(s.get('minArea')||0),max=Number(s.get('maxArea')||Infinity),area=a.area*(a.unit==='ha'?10000:1);
 return (!s.get('province')||s.get('province')===p.province)&&(!s.get('industry')||a.industries.includes(s.get('industry')!))&&(!s.get('transaction')||a.transaction===s.get('transaction'))&&(!s.get('q')||`${a.name.vi} ${a.name.en} ${a.name.zh||''} ${p.name.vi}`.toLowerCase().includes(s.get('q')!.toLowerCase()))&&area>=min&&area<=max;
}
export function DiscoveryFilters({asset=false}:{asset?:boolean}){
 const {language,parks}=useApp(),[s,setS]=useSearchParams(),t=(vi:string,en:string,zh:string)=>emptyCopy(language,vi,en,zh);
 const [min,setMin]=useState(s.get('minArea')||''),[max,setMax]=useState(s.get('maxArea')||'');
 const savedMin=s.get('minArea')||'',savedMax=s.get('maxArea')||'';
 useEffect(()=>{setMin(savedMin);setMax(savedMax)},[savedMin,savedMax]);
 const valid=(a:string,b:string)=>(!a||+a>0)&&(!b||+b>0)&&(!a||!b||+a<=+b);
 const set=(key:string,value:string)=>setS(old=>{const next=new URLSearchParams(old);if(value)next.set(key,value);else next.delete(key);return next},{replace:true});
 const range=(a:string,b:string)=>{setMin(a);setMax(b);if(valid(a,b))setS(old=>{const next=new URLSearchParams(old);a?next.set('minArea',a):next.delete('minArea');b?next.set('maxArea',b):next.delete('maxArea');return next},{replace:true})};
 const toggle=(key:string,value:string)=>setS(old=>{const next=new URLSearchParams(old),all=next.getAll(key);next.delete(key);(all.includes(value)?all.filter(x=>x!==value):[...all,value]).forEach(x=>next.append(key,x));return next},{replace:true});
 return <section className="discovery-extra"><div className="form-grid">{asset&&<label>{t('Từ khóa','Keyword','关键词')}<input value={s.get('q')||''} onChange={e=>set('q',e.target.value)}/></label>}<label>{t('Tỉnh/thành phố','Province','省市')}<select value={s.get('province')||''} onChange={e=>set('province',e.target.value)}><option value="">{t('Tất cả','All','全部')}</option>{[...new Set(parks.filter(p=>p.publicationStatus==='published').map(p=>p.province))].map(p=><option key={p}>{p}</option>)}</select></label><label>{t('Diện tích từ (m²)','Area from (m²)','面积下限 (m²)')}<input type="number" value={min} onChange={e=>range(e.target.value,max)}/></label><label>{t('Diện tích đến (m²)','Area to (m²)','面积上限 (m²)')}<input type="number" value={max} onChange={e=>range(min,e.target.value)}/></label>{asset&&<><label>{t('Ngành','Industry','行业')}<select value={s.get('industry')||''} onChange={e=>set('industry',e.target.value)}><option value="">{t('Tất cả','All','全部')}</option>{[...new Set(parks.flatMap(p=>p.suitableIndustries))].map(i=><option key={i} value={i}>{industryLabel(i,language)}</option>)}</select></label><label>{t('Hình thức','Transaction','交易方式')}<select value={s.get('transaction')||''} onChange={e=>set('transaction',e.target.value)}><option value="">{t('Tất cả','All','全部')}</option><option value="lease">{t('Thuê','Lease','租赁')}</option><option value="sale">{t('Mua','Purchase','购买')}</option></select></label></>}</div>{!valid(min,max)&&<p role="alert">{t('Diện tích phải dương và từ không lớn hơn đến. Giữ kết quả theo khoảng hợp lệ trước.','Area must be positive and minimum cannot exceed maximum. Previous valid range is retained.','面积须大于零且下限不超过上限，保留上次有效范围。')}</p>}{!asset&&<div className="discovery-checks"><label><input type="checkbox" checked={s.has('available')} onChange={e=>set('available',e.target.checked?'yes':'')}/>{t('Còn diện tích công khai','Publicly available land','有公开可用土地')}</label>{[['electricity',t('Điện','Electricity','电力')],['water',t('Nước','Water','供水')],['wastewater',t('Nước thải','Wastewater','污水')]].map(([key,label])=><label key={key}><input type="checkbox" checked={s.getAll('utility').includes(key)} onChange={()=>toggle('utility',key)}/>{label}</label>)}{[['port',t('Cảng','Port','港口')],['airport',t('Sân bay','Airport','机场')],['road',t('Đường chính','Major road','主干道路')]].map(([key,label])=><label key={key}><input type="checkbox" checked={s.getAll('connection').includes(key)} onChange={()=>toggle('connection',key)}/>{label}</label>)}</div>}<button className="button" onClick={()=>{setMin('');setMax('');setS({},{replace:true})}}>{t('Xóa bộ lọc','Clear filters','清除筛选')}</button></section>;
}
