import {CalendarDays,Globe2,ArrowUpRight} from 'lucide-react';
import {useApp,tr} from './AppContext';
import {emptyCopy,SafeImage,StatePanel} from './EmptyStates';
import {mockTradeExpos,visibleVigExpos} from './tradeExpoFixtures';
export {mockTradeExpos,visibleVigExpos} from './tradeExpoFixtures';
export function TradeExpoSection(){const {language}=useApp(),t=(vi:string,en:string,zh:string)=>emptyCopy(language,vi,en,zh),rows=visibleVigExpos(mockTradeExpos);
 const date=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString(language==='vi'?'vi-VN':language==='zh'?'zh-CN':'en-GB');
 return <section className="vig-tradexpo-section"><div className="section-heading"><h2>{t('Triển lãm thuộc VIG','VIG Expos','VIG展会')}</h2><p>{t('Thẻ theo mẫu TradeXpo Arobid · Toàn bộ chương trình và số liệu dưới đây là dữ liệu mô phỏng.','Cards follow Arobid TradeXpo · All programs and figures below are mock data.','沿用Arobid TradeXpo卡片样式 · 以下展会与数值均为模拟数据。')}</p></div><div className="vig-tradexpo-grid">{rows.map(e=><article className="vig-tradexpo-card" key={e.id}><div className="tradexpo-cover"><SafeImage src={e.image} alt={tr(e.title,language)}/><span className={'tradexpo-status '+e.status}>{e.status==='upcoming'?t('Sắp diễn ra','Upcoming','即将开始'):e.status==='live'?t('Đang diễn ra','Live','进行中'):t('Đã diễn ra','Archived','已结束')}</span><span className="tradexpo-countries"><Globe2 size={14}/>{e.countries} {t('quốc gia','countries','个国家')}</span><div className="tradexpo-dates"><CalendarDays size={22}/><div><small>{t('Thời gian tổ chức','Duration','举办时间')}</small><b>{date(e.start)} – {date(e.end)}</b></div></div></div><div className="tradexpo-card-body"><h3>{tr(e.title,language)}</h3><p>{tr(e.industries,language)}</p><div className="tradexpo-stats">{[[t('Đơn vị tiềm năng','Potential exhibitors','潜在参展商'),e.potential],[t('Đơn vị triển lãm','Booked exhibitors','已订展位参展商'),e.booked],[t('Khách tham quan','Registered visitors','登记观众'),e.visitors],[t('Sản phẩm/Dịch vụ','Products/Services','产品/服务'),e.products]].map(([label,value])=><div key={label}><b>{Number(value).toLocaleString(language==='vi'?'vi-VN':language==='zh'?'zh-CN':'en-US')}</b><span>{label}</span></div>)}</div>{e.publicUrl?<a className="button primary" href={e.publicUrl}>{t('Xem trên TradeXpo','View on TradeXpo','在TradeXpo查看')}<ArrowUpRight size={16}/></a>:<button className="button" disabled>{t('Expo mẫu — chưa có liên kết nguồn','Mock Expo — source link unavailable','模拟展会—暂无来源链接')}</button>}</div></article>)}</div>{!rows.length&&<StatePanel title={t('Chưa có Expo thuộc VIG','No VIG Expos yet','暂无VIG展会')} text={t('Các Expo công khai thuộc VIG sẽ hiển thị tại đây.','Public VIG Expos will appear here.','属于VIG的公开展会将在此显示。')}/>}</section>;
}
