import type {LocalizedText} from './types';
export interface ExpoCardData {id:string;ownerId:string;isPublic:boolean;title:LocalizedText;industries:LocalizedText;image:string;status:'upcoming'|'live'|'ended';countries:number;start:string;end:string;potential:number;booked:number;visitors:number;products:number;publicUrl?:string}
export const mockTradeExpos:ExpoCardData[]=[
 {id:'expo-cn',ownerId:'VIG',isPublic:true,title:{vi:'VIG — Triển lãm đầu tư công nghiệp Việt Nam – Trung Quốc',en:'VIG Vietnam–China Industrial Investment Expo',zh:'VIG越中工业投资展'},industries:{vi:'Điện tử • Bán dẫn • Hạ tầng công nghiệp',en:'Electronics • Semiconductors • Industrial infrastructure',zh:'电子 • 半导体 • 工业基础设施'},image:'/images/industrial-parks/electronics-semiconductor.png',status:'upcoming',countries:2,start:'2026-10-15',end:'2026-10-25',potential:72,booked:28,visitors:1260,products:96},
 {id:'expo-kr',ownerId:'VIG',isPublic:true,title:{vi:'VIG — Triển lãm chuỗi cung ứng và logistics',en:'VIG Supply Chain & Logistics Expo',zh:'VIG供应链与物流展'},industries:{vi:'Kho vận • Cảng biển • Chuỗi cung ứng',en:'Warehousing • Seaports • Supply chain',zh:'仓储 • 海港 • 供应链'},image:'/images/industrial-parks/logistics-port.png',status:'live',countries:3,start:'2026-09-01',end:'2026-09-15',potential:64,booked:36,visitors:2480,products:140},
 {id:'expo-global',ownerId:'VIG',isPublic:true,title:{vi:'VIG — Triển lãm công nghiệp xanh',en:'VIG Green Industry Expo',zh:'VIG绿色工业展'},industries:{vi:'Năng lượng sạch • Sản xuất xanh • KCN sinh thái',en:'Clean energy • Green manufacturing • Eco-industrial parks',zh:'清洁能源 • 绿色制造 • 生态工业园'},image:'/images/industrial-parks/green-energy.png',status:'ended',countries:4,start:'2026-08-10',end:'2026-08-20',potential:80,booked:42,visitors:3200,products:168},
 {id:'outside-vig',ownerId:'OTHER',isPublic:true,title:{vi:'Expo ngoài VIG — không hiển thị',en:'Non-VIG Expo — excluded',zh:'非VIG展会—不显示'},industries:{vi:'',en:'',zh:''},image:'',status:'upcoming',countries:1,start:'2026-10-01',end:'2026-10-02',potential:1,booked:1,visitors:1,products:1},
];
export const visibleVigExpos=(rows:ExpoCardData[])=>rows.filter(e=>e.ownerId==='VIG'&&e.isPublic);
